### ISSUE TITLE
Mira.Frame Glitching and blinky after lastest updates

### ISSUE THREAD

**Issue by CarloCattano** [Cycling74/miraweb#50] opened 2017-02-16 19:56 UTC
Hi there . Just updated both max and miraweb. Now in all of my android devices , with both native web browser or chrome , the UI screen appears for a while , then as soon as the screen is touched , it becomes either tottaly black , blinking fading between black and white fastly , or just stays in full black out , sliders and objects still functional but invisible .
Any idea what could be the solution ? 

Thanks !

**Comment by starakaj** [comment] 2017-02-16 21:20
Hey Carlo, I can't seem to reproduce this in the android emulator. What device are you running on? What OS?

**Comment by fde31** [comment] 2017-02-16 21:28
Might also be helpful if you could share the patch. The new MiraWeb
supports poster and frame color backgrounds so maybe there is something
along these lines triggering it.

**Comment by CarloCattano** [comment] 2017-02-16 21:54
-Tablet lenovo A7600-F , Android version 4.4.2 kernel 3.4.67
-Smartphone Alcatel one Touch 5025D, Android version 5.1 kernel 3.10.72

the patch is the default miraweb Launcher and from there I connect to the same Ip and port given. 
Was working just before updating . I attach also a video , but camera frame rate cant see the actual blinking

https://drive.google.com/open?id=0B4P3snRTyoRbZkY2VGYtS1pCRXM

**Comment by fde31** [comment] 2017-02-16 23:51
OK. I tested on Chrome, FF and Safari on Mac OSX and couldn't reproduce. Then went ahead and so far all fine on an iPad (iOS 10) and iPhone (iOS 9). Then went ahead and took everything for a spin on a Nexus 9 (Android 7.0) in Chrome => no flickering, all smooth and fine.

I have a ZTE Blade L5 and will double check 2morrow.

In the meantime can you give us your Max support info? What version of MiraWeb does the PM report? Also do u have a Mira package in your Documents/Max 7/Packages folder?

Thx for helping us tracking this down!

**Comment by CarloCattano** [comment] 2017-02-17 08:12
Max support clipboard :  http://pastebin.com/MyaMFt7w

Miraweb & mira folders are in the max7/Packages/ folder.

The max console doesnt give any report , everything goes "fine". With laptop there is no problems.
I will try to reinstall the package and/or  clean the preferences in max?

Thanks for your help

**Comment by CarloCattano** [comment] 2017-02-17 08:22
Tried to downgrade to miraweb 1.0.1 but without any change , the problem is still there.
The current version , and the one that started this issue is V 1.2.0

**Comment by fde31** [comment] 2017-02-17 08:38
I'll get to this in a bit. In the meantime, can you remove the Mira
package from your Packages folder (max ships with an internal one by now),
install MiraWeb 1.2.0 again and clear the cache on your devices' browser?

Thanks

**Comment by CarloCattano** [comment] 2017-02-17 08:54
Did al the suggestions as @fde31 says .
Still having same issue in both devices and two different browsers with fresh clean cache.
:-( 
Max console acts normal : 
Mira Initialized, package version: 1.2.0
websocket connection available at ws://192.168.2.118:8086

**Comment by fde31** [comment] 2017-02-17 09:05
OK. Somewhat good news: I can reproduce on a ZTE L5 Blade with Android 5.1.
I’ll investigate

Am 17 Feb 2017 um 09:54:14, CarloCattano (notifications@github.com) schrieb:

Did al the suggestions as @fde31 <https://github.com/fde31> says .
Still having same issue in both devices and two different browsers with
fresh clean cache.
:-(
Max console acts normal :
Mira Initialized, package version: 1.2.0
websocket connection available at ws://192.168.2.118:8086

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Cycling74/miraweb/issues/50#issuecomment-280592260>,
or mute
the thread

**Comment by fde31** [comment] 2017-02-17 09:47
It's in fact related to the change where started drawing the background color in a way it matches  patcher/mira.frame in the patcher. I have checked in a fix for this on the `fde/fixAndroidFrameBackground` branch basically making the PIXI renderer transparent again and applying the background tint on the DOM level. This change should be fine also given the fact that the bg color doesn't change frequently etc etc.

We'll run some tests and ideally push a hotfix release via the PM very very quickly!

**Comment by fde31** [comment] 2017-02-17 09:57
@CarloCattano if you wanna run a test on your end I've built a pre-release version of the MiraWeb client incl. a fix. If you manage to run a simple server on your computer to host the files and access from your Androids that would be ace. Just leave the MiraWeb package in Documents/Max 7/Packages untouched and simply just access the index.html file included in this .zip and use it as normally (just adjusting the port in the dialogue). Hope that makes sense?

[mw_androidflickeringfix.zip](https://github.com/Cycling74/miraweb/files/782841/mw_androidflickeringfix.zip)

**Comment by CarloCattano** [comment] 2017-02-17 19:04
Thanks for the help , glad that you could find the spot !
Im a little bit lost about running it in a server. Could it be uploaded and then accesed from <script src="http...etc" ??
Or any nice article or way to find the information to do it with nodes.js?
Yet not feeling home with lined code but my will is strong!

**Comment by benbrackenc74** [comment] 2017-02-17 20:01
@CarloCattano we've just released a new Miraweb Package via the Max Package Manager, give it a go and let us know if you run into any problems!

**Closed by benbrackenc74** 2017-02-17 20:01 UTC
Labels: Status: Fixed, Type: Bug

**Comment by CarloCattano** [comment] 2017-02-17 20:12
I have no words!! working 100% stable and sweet .
This is the fastest bugfix i ever saw or could think off EVER!
You just saved me and hundreds of other people that will use this with old android devices👍 👍 👍   
/* Thanks = [uzi 1000] */
