### ISSUE TITLE
Int/Float: triangle 0 does not work.

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#112] opened 2017-08-29 15:16 UTC
Triangle shows in MiraWeb, but not Mira App:

<pre><code>
----------begin_max5_patcher----------
659.3oc2WssjhCBD84juhT7bVqPt69qXYYQTzgYHfEg35TS4+9xkDGc1X7ZM
Sb8gfzzA5tOmb.9v0ATv2hq.d+1ahmiyGtNNFSZCNM8c.knsyonJia.JYCdT
Ekr.K.91w2fDLTI9qCOANs0CVcIgQwRyT.aLV8B+OsuWPis0H47WHrUyD34R
aXElGMJv2CFYZhFqeNNYTf2zCmm5xBU.cvLorvqksqYXiUxBSTxKd8WPHX+h
JTggDKlgYnBJ9vfbs.WgYRjjvYmLnBZdrOjrqr780Xq6.fuGXIkiTu99vFsA
uXFRJEjhZI9y+U0T8aJ+55KsFyW1Zt09gANkyV0OFbj6pRlP1k+c4baZDzwX
0LhrR9tslEXGemq6mMlm6b8e3rqdoVcQihf8SiNOgI3RHLCFn+4C2WPPzSh5
5AePJJv7LCUHNZThhJDq6Dlc+JJiuGAkDCiDN1RO+2XZ.vqNFBNGw5.zbfSq
tVoDXdnAqxRz7mXCVEmcMRI4OIJImBCGnvsp3nJ8cg01ulmD1u9wRtnDY.4z
dP+PyFIgvDcShYu+vvqA8SuDzeecAz5sBYQrUziU25VMAllaiwzK+3IEpI+6
fX8UnnGhUiqcK4zF9QcLFgsgTQZqn2OwpYyfSSrhld0hHVZDLO+VoQYeWzHX
93AKMJ5hoQ+zbnyJNAebhSvzfakUkbarpg.W.9+jjxspmXueysf7QOsH+yhD
PIQfFsTO6chtspwjULtBXoj4ucNPOvJPGXNPZXhZ6d8uTe6YTOA1GzwcaaCn
Bz72VI30rE6y4ljzLY.z50avhJ09Dl7Tmkpb7Ut4lRY9ltDlsqojBDXcQz5e
rwBRnxCoJIpEVzYaZLv9pb0cQY0jl0Vsx6b+KL23j1H
-----------end_max5_patcher-----------
</code></pre>

**Comment by fde31** [comment] 2017-08-30 22:09
I guess that's a duplicate of #101 

noted that it affects int and float

**Closed by fde31** 2017-08-30 22:09 UTC
