### ISSUE TITLE
Using Xebra in a node server instead of clients browser

### ISSUE THREAD

**Issue by CarloCattano** [Cycling74/miraweb#129] opened 2017-11-18 15:44 UTC
I font know if this is possible. All my tests have failed and I couldn't find any documentation about it.

I prefer to use Xebra to send max data to the node app, then from there I will send it to the clients using socket.io .  

Its useful when you need to process the data each client receives in different ways. and perhaps more efficient for a multi user (+20) experience.

**Comment by fde31** [comment] 2017-11-20 20:38
Yeah. This is a duplicate of #84 currently xebra-communicator relies on a global WebSocket implementation like the ones offered by browsers. I'll look into it as it would be ace to have Xebra available in Node I guess.

**Comment by fde31** [comment] 2017-11-20 20:39
closing out as duplicate. any further work/discussion should be done in #84 thx!

**Closed by fde31** 2017-11-20 20:39 UTC
Labels: Status: Duplicate
