### ISSUE TITLE
Client build error?

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#118] opened 2017-09-06 04:02 UTC
Hi, trying to build using the instructions [here](https://github.com/Cycling74/miraweb)
But I get the attached when running any of the build commands from /packages
Never did this before so maybe I'm doing this incorrectly...Any advice?
[npm-debug.log.zip](https://github.com/Cycling74/miraweb/files/1279720/npm-debug.log.zip)

**Comment by 1offby** [comment] 2017-09-06 04:04
From the error dump in Terminal:
Tell the author that this fails on your system:
npm rimraf ./build && webpack --config webpack/release.config.js

**Comment by benbrackenc74** [comment] 2017-09-06 18:47
@1offby it would be good to know exactly what you are doing. Can you provide a set of steps?

**Comment by 1offby** [comment] 2017-09-06 18:59
@benbrackenc74 I figured out how to accomplish my goal without building. This is not a priority for me.

I got this result by following the build instructions on the homepage for this repository on an unchanged clone of https://github.com/Cycling74/miraweb.git. I was interested to see if it worked.
`$> npm run setup`
and
`$> npm run clean`
were successful
then I tried
`$> npm run build-release`
from /packages. I also tried that command from /miraweb, and a couple other things, and got results like those in nom-debug.log above.

**Comment by fde31** [comment] 2017-09-07 14:47
Hey @1offby 

let me give you some background first and how MW is setup wrt packages in the repo and then follow up with written down instructions on how to build each of them and MiraWeb as a whole.

Maybe this helps and you can follow the direct steps or see what differs from the setup you've been running.

**/ Packages ** 

MiraWeb itself constists of 3 parts:

* Xebra-Communicator (the communication layer between Max and Xebra.js)
* Xebra.js (the state / sync layer on top of Xebra-Communicator)
* MiraWeb (the application build on top of Xebra.js in order to interact with Max in a Mira-like fashion)

**/ MonoRepo **

In order to keep the work easily maintainable and testable, esp across branches, we decided to move to a monolithic repository approach. This means we have the MiraWeb application itself and the included, mandatory packages in the same repository. Keep in mind though, that Xebra.js is also distributed by itself in order to allow people to build different applications on top of the same communication and state layer.

In order to simplify the process the MonoRepo comes with a bunch of helper scripts that are meant to be run from the root of the repository. Additionally to that, each contained package comes with additional, package local scripts.

I hope this makes sense so far?

**/ Setup **

As written in the repository the initial way to setup MiraWeb is by

```
# Clone Repository
$>    git clone git@github.com:Cycling74/miraweb.git

# Setup Repository (symlinks, dependencies etc)
$>    npm run setup

# Build MiraWeb Release version
$>   npm run build-release

# If you'd like to work on MiraWeb this gives u locally running dev copy, served via a server
# watching for changes on disk. It will open your browser (blank until initial build done) and
# from there on, keep serving and reload on changes
$>    npm run serve
```

Keep in mind that MiraWeb in the repo consumes the Xebra.js sources and not the pre-built distributables. This way changing Xebra.js will trigger a rebuild/reload of MiraWeb being served.

Looking at the debug output I'm not 100% what's causing the issue. It might be a permission thing but I'm not 100%.

Can u try the above statements again, without `cd` into a subfolder within the repo and tell what u experience. If you still encounter the issue. I'd advise to run the inherited steps of `build-release` in a separated fashion to test each step separately. That would be:

```
$>    rm -rf ./build
$>    webpack --config webpack/release.config.js
```

Can you additionally just let me know what OS you're running on?

**Comment by 1offby** [comment] 2017-09-08 14:14
@fde31 Many thanks for this explainer.  
To be clear: I did try running the build process without `cd` into a subfolder. I only did `cd` when the build didn't work.  
I am running High Sierra beta 9.  

After a fresh clone of https://github.com/Cycling74/miraweb.git here's the result of re-trying the repository build steps you listed:  

NOTE: The steps listed above do not include  

`$> npm run clean`  

Which is part of the build process on the homepage for the repository.  

`$> npm run setup`
> miraweb@1.2.2 setup /git/miraweb
> node ./.bin/setup.js
> 
> Setting up repository. This might take a bit...
> 
> ✓ Installing NPM dependencies
> ✓ Install and setup included package dependencies
> ✓ Link Xebra.js
> ✓ Installing PIXI dependencies
> ✓ Building lib version
> 
> Success! Additional debug has been written to /git/miraweb/mw_debug.log

Debug log: 
[mw_debug.log_1.zip](https://github.com/Cycling74/miraweb/files/1288072/mw_debug.log_1.zip)

2:

`$> npm run build-release`

> miraweb@1.2.2 build-release /git/miraweb
> rimraf ./build && webpack --config webpack/release.config.js
> 
> Hash: 1279ca05d01f32aa36b7
> Version: webpack 2.3.2
> Time: 65212ms
>                                     Asset       Size  Chunks                    Chunk Names
>             ./static/apple-touch-icon.png    5.28 kB          [emitted]         
>       ./static/apple-touch-icon-57x57.png    1.56 kB          [emitted]         
>       ./static/apple-touch-icon-72x72.png    1.97 kB          [emitted]         
>       ./static/apple-touch-icon-76x76.png    2.09 kB          [emitted]         
>     ./static/apple-touch-icon-114x114.png    3.18 kB          [emitted]         
>     ./static/apple-touch-icon-120x120.png    3.33 kB          [emitted]         
>     ./static/apple-touch-icon-144x144.png    4.11 kB          [emitted]         
>     ./static/apple-touch-icon-152x152.png    4.46 kB          [emitted]         
>     ./static/apple-touch-icon-167x167.png    5.06 kB          [emitted]         
>     ./static/apple-touch-icon-180x180.png    5.28 kB          [emitted]         
>       ./static/apple-touch-icon-60x60.png    1.61 kB          [emitted]         
> ./static/apple-touch-icon-precomposed.png    5.28 kB          [emitted]         
>                ./static/favicon-16x16.png  432 bytes          [emitted]         
>                ./static/favicon-32x32.png  925 bytes          [emitted]         
>                      ./static/favicon.ico    33.3 kB          [emitted]         
>                           ./static/.cache    2.06 kB          [emitted]         
>                     ./static/c74_logo.png    8.91 kB          [emitted]         
>                  ./static/github_logo.png    4.27 kB          [emitted]         
>                 ./static/miraweb_logo.png    13.3 kB          [emitted]         
>                                    app.js    1.22 MB       0  [emitted]  [big]  main
>                                index.html    1.71 kB          [emitted]         
>    [1] ./\~/react/react.js 56 bytes {0} [built]
>   [42] ./src/js/actions/createAction.js 762 bytes {0} [built]
>   [69] ./\~/react/lib/React.js 5.08 kB {0} [built]
>   [96] ./src/js/actions/xebraState.js 794 bytes {0} [built]
>  [142] ./src/js/lib/assets.js 3.76 kB {0} [built]
>  [230] ./src/js/objects/factory.js 1.04 kB {0} [built]
>  [381] ./src/js/mira.jsx 1.38 kB {0} [built]
>  [382] ./src/theme/index.scss 1.19 kB {0} [built]
>  [393] ./src/js/index.js 1.01 kB {0} [built]
>  [432] ./\~/css-loader!./\~/postcss-loader?{}!./\~/sass-loader!./src/theme/index.scss 77.2 kB {0} [built]
>  [688] ./\~/react-dom/index.js 59 bytes {0} [built]
>  [702] ./\~/react-dom/lib/ReactDOM.js 5.17 kB {0} [built]
>  [770] ./\~/style-loader/addStyles.js 6.91 kB {0} [built]
>  [771] ./\~/url-loader!./src/assets/hatching-horizontal.svg 5.75 kB {0} [built]
>  [777] ./\~/url-loader!./src/assets/multitouch-touch.png 5.3 kB {0} [built]
>     + 848 hidden modules
> 
> WARNING in ./\~/gyronorm/dist/gyronorm.complete.js
> Module not found: Error: Can't resolve 'vertx' in '/git/miraweb/node_modules/gyronorm/dist'
>  @ ./\~/gyronorm/dist/gyronorm.complete.js 132:20-30
>  @ ./src/js/lib/motion.js
>  @ ./src/js/stores/xebraState.js
>  @ ./src/js/components/connectDialog.jsx
>  @ ./src/js/components/app.jsx
>  @ ./src/js/mira.jsx
>  @ ./src/js/index.js
> Child favicons-webpack-plugin for "../[hash].json":
>                                         Asset       Size  Chunks             Chunk Names
>         ./static/apple-touch-icon-167x167.png    5.06 kB          [emitted]  
>           ./static/apple-touch-icon-57x57.png    1.56 kB          [emitted]  
>           ./static/apple-touch-icon-72x72.png    1.97 kB          [emitted]  
>           ./static/apple-touch-icon-76x76.png    2.09 kB          [emitted]  
>         ./static/apple-touch-icon-114x114.png    3.18 kB          [emitted]  
>         ./static/apple-touch-icon-120x120.png    3.33 kB          [emitted]  
>         ./static/apple-touch-icon-144x144.png    4.11 kB          [emitted]  
>         ./static/apple-touch-icon-152x152.png    4.46 kB          [emitted]  
>           ./static/apple-touch-icon-60x60.png    1.61 kB          [emitted]  
>         ./static/apple-touch-icon-180x180.png    5.28 kB          [emitted]  
>                 ./static/apple-touch-icon.png    5.28 kB          [emitted]  
>     ./static/apple-touch-icon-precomposed.png    5.28 kB          [emitted]  
>                    ./static/favicon-16x16.png  432 bytes          [emitted]  
>                    ./static/favicon-32x32.png  925 bytes          [emitted]  
>                          ./static/favicon.ico    33.3 kB          [emitted]  
>                               ./static/.cache    2.06 kB          [emitted]  
>        [0] ./\~/favicons-webpack-plugin/lib/favicons.js?{"outputFilePrefix":"./static/","icons":{"android":false,"appleIcon":true,"appleStartup":false,"coast":false,"favicons":true,"firefox":false,"opengraph":false,"twitter":false,"yandex":false,"windows":false},"background":"#595959","persistentCache":true,"appName":"MiraWeb"}!./src/assets/miraweb_logo.png 1.95 kB {0} [built]
> Child html-webpack-plugin for "index.html":
>        [0] ./\~/lodash/lodash.js 540 kB {0} [built]
>        [1] ./\~/html-webpack-plugin/lib/loader.js!./src/index_tmpl.html 876 bytes {0} [built]
>        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
>        [3] (webpack)/buildin/module.js 517 bytes {0} [built]

At this point there is a build directory within /miraweb:
<img width="326" alt="build_directory" src="https://user-images.githubusercontent.com/1762758/30215373-ae082330-9464-11e7-92f9-76a6ab7bbe01.png">
Including this file: 
[app.js.zip](https://github.com/Cycling74/miraweb/files/1288111/app.js.zip)

So maybe this worked. Perhaps skipping `$> npm run clean`  made a difference?

As mentioned I did get the results I was initially looking for without building, so I can't test this result at the moment. However, happy to do so later and interested in how this progresses.

**Comment by fde31** [comment] 2018-11-07 10:40
Can't reproduce and in fact was able to build without any issues. Closing out

**Closed by fde31** 2018-11-07 10:40 UTC
