### ISSUE TITLE
live.text pictures do not update when empty

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#48] opened 2017-02-11 06:54 UTC
Max 7.3.2 beta 6bf7de6 x64
Mira v 1.2.0
Miraweb v 1.1.0
mac OS 10.12.3
iOS 10.2.1

Sending the message "pictures" with no argument clears pictures displayed in live.text.
This message works in Max and the Mira app but not in MiraWeb.

Workaround: Load a blank .svg to clear contents

<pre><code>
----------begin_max5_patcher----------
816.3ocyW90aaCBD.+4jOEH+zlTlk+SrSReHRUU6w9xdcZpBaSSn0Fh.bVpp
528c.1I3UWmzLk1kGLliCt69wAmyyiG4kw2QjdnqP+DMZzyiGMxHRKXTS+Qd
U3c4kXoQMuJhThWQ7lXGSQ1oLx2PyU0BhDgKJx4k9xsqbdsUcVcEkURTl0Jp
Q3FrJeMks5NAIWY8k3zH+fInn4w5lvYSM8.Yne0LIZgwr7rG9VXpyxyqUsqe
X65CtEgovJJm0wFIN1Hn4wdCXWH0SaHV0871OjT8ToQpmmVvKiGqeL4DIXNu
pBbmWQvqA.hKuBcsBIUjMnXTIcKwWONhxPUTA92jLXLZYIZMVhnUNaDcHa3a
S1nEKLQcfEoKrMAuAYS5mrACS1t13Uj8xfuuuaC3.jhiBPM5X7+I5ElN+Tn2
zgo2kgCw9naJo4Ot7bisHy4gj4CFZQmUhQbPfiI9fRLhNWfz3sVRbDdD9YrU
GBQFmw.GFo3nas42u6nLN0rmjXeFLTXt3yHJ+BNCrELWSMEpDUxywJLoPen9
V7tk.CTvDkK+AQxqE4D4xalMcIEjJtGCc+Z6ZVRAXwqYJ2xOm74iYFzzjHXA
Ubb+fZ1kDTGqD7YVrMLxzjDOTs1jyqTaSN1zjO1RsG+iUbSsb6blLr8VhngX
3zgY3EiF6qF1Z+sXACWQ5evS8XQX3La1ioYVn9Yp6wh8ok1ngW4iE9YkX1iV
P+ZQ8dCa+P6vVh.hD3.+cDFNyBoVmtVRZ7ggw7jNnFukTbGVoDzrZE4vaxFB
2fXMEKqI76aE2J20mJ4rUuIo6nobMWnNMUac8ndFqB13MAqePOiR.F1DzfyG
pCbnMBBdqtl7p1l26QNnJj+8ZK0ahTv.2uF6uP+KsMKJJAt0P+CjDNuygoUL
NLQcUc2sTmzki78IY37GWIfJAlYD5DmFaXJT7W+sHiGqk2M3sUbZysa92HnC
tZAA9fcl4BQWk5nyZZQAg45eEToNK13cA8tKbptSx+UdyzKn2X24va1rkHjM
KowQfDzG3Bc2YSLcoLa2XSWAYKsUeyYIOr.xMUj8WY3sK0dmsWEufHX0zlrF
vxuL9O.PzR56
-----------end_max5_patcher-----------
</code></pre>

**Comment by starakaj** [comment] 2017-02-11 13:48
Good catch. I'll add that this is broken for live.tab as well. Probably worth mentioning that fpic does not work the same way as these objects---sending the pic message to fpic does not clear the image in the fpic. However, reloading the patch after clearing the image this way will blank out the fpic. Not sure how much of this behavior (which seems slightly buggy anyway...) we want to reproduce for fpic and miraweb.

**Comment by fde31** [comment] 2017-05-04 20:34
OK. I tackled this in both, _xebra.js_ and _MiraWeb_, so that we now have the following state:

* sending an empty or one value only `pictures` msg to _live.text_ clears the according resources/images
* sending _fpic_ an empty `pic` msg clears the resource (as in Mira App, however notice the diff to Max here as discussed earlier today)

However, I noticed that setting the `pictures attr` of _live.tab_ to an empty value or sending an empty `pictures` does **not** trigger a msg being sent to the client so that neither MiraWeb nor Mira App will update accordingly.

@benbrackenc74 @starakaj this might require a change on the Max side, will take a glimpse, but as the code for _live.tab_ is basically reconstructing all resources on a `pictures attr` change this should _just work_ 

I'll make PRs for this already but let me know if you're not OK with the outlined status. The work is checked in on the `fde/clear_resources` branch here and in the xebra.js repo

**Comment by 1offby** [comment] 2017-05-05 19:06
Yay, thank you. Finally my blank.svg can get a rest.

**Comment by starakaj** [comment] 2017-05-09 14:29
@fde31 yes, this will require a change to live.tab itself to fix, as it's a bona fide Max bug. Try attaching an attrui to a live.tab object and setting it to the "pictures" attribute. Then, send the live.tab object the message "pictures". This clears the live.tab object, but the attrui won't update. Basically, setting pictures to an empty value doesn't cause the attribute to send a Max notification.

**Comment by starakaj** [comment] 2017-05-09 18:01
k, so turns out was a bug in both attrui and libXebra as well. Both don't seem to handle attributes with length 0 very well. Both should be fixed now in Max commit 3544c8f

**Comment by starakaj** [comment] 2017-05-09 18:01
Oh, also, @fde31's fixes work great.

**Comment by benbrackenc74** [comment] 2017-05-09 22:12
this works well, and will be available in Max 7.3.4

**Closed by benbrackenc74** 2017-05-09 22:12 UTC
Labels: Component: MiraWeb, Status: Needs Testing, Type: Bug

**Comment by fde31** [comment] 2017-05-10 06:35
perfect. Totally forgot to add the additional test patcher I used here:

`
----------begin_max5_patcher----------
1296.3oc0YszbihCD9ryuBJN6wCRhm6gop4GvddOjMkKYrrix.RTfHUlZp4+
9pWXKR7C1XE1rGrEsPf95O0cqVM+5tEga3uP5BC9if6CVr3W2sXgtKUGKrxK
BqwuTVg6zCKrjWWSXhvkl6IHuHz8+UXP4iX1dR.sFuW9NsCnAKJejx1utkTJ
LSTZT5pnkA.XwpDYSRjRBJ+O3A6Cw5qorJhPOk.amcheVQzy0v6ltUKx27zW
RiBO9r7dwvCGo5722cm5ukSTEqIccRU3MpXCsTz2R5B1IuZ8lpdxpF1dizi7
9NGQJSPZo71UO0re38TQYjRdOS+xf1NMPU7yFhgaBCOPBWf4R.JlCFmojPIm
i4fSh4.ml4.uCl6bFGe4aALtfVRjMGLSXA+IsE+WjMAX1V80euo4uYa6IABd
.VHZGFp7YC1PjTQfnEy5poBAY6Eo0SxcPscVJR2jnYRD5lr5RJ7mU2YcrPAk
UDb6T7qLZHHyXj3C+pjrYPCAAcDwjiaDm6Q0KY9BaD9Nc4MKpnBUShw3EdSd
7IP+4wOsXkSH536JPXlwF.B7Aq3w3fUzmIqD3MCuwmwsLbMYz8tG7fyDtVEF
qacijxjtHXAkyz1gmkcVZ9sqhiEWjphSh0VNZ6mBiuSVtCU0fakXSthrlvva
LDzfyibYytR516I8ybTBKHT2E8Vh9L77vH6vOS1tVE9mtoWPNdUmkvsLthUk
aAy2Mz8P+tZTEms+ULuxBc4aGY2i7VwzF5vx.7D2qVZGnYkUQm3tDoJaW.kf
GnV.ksPaK5v53nGpmQEGrbiL2WaONz3OW12myHDE4lUhNqtazYLNcVBQ4qvQ
VF.hzAh.fHODOJNdFofgjYuI0OSuSEHxGQiiQe7YkJyr5PdGA38XJK75KwQE
9K6iX3LjbEzM8wqqf.DziJXz7l830UujH+ocnb+oc6tTz2mnh00X41fubQ2P
f1zLWmhHH2nnwot6zKmCWc4jprqBdtnv1dw8B9Np3+Y4NBiz6Skfx7WxinY3
PzeM14XRWOdkUKAIdzfG9Y+zRVsNt.3sSKAKlkchLAo2vEOd8CBOnkodbuHz
rW.sCN121RMJWWEwAu4aasNeFVqG1PtSpOUjquwkUOAo9qZovOQU0wpenTOV
0JX5+YFyddWJTdg+1kBh7cINNdB4STiC4McJxwoKgwko.c49hLYxXOcgxO22
ktvkhNyVbv4q5DG4rOOEnH3AOT2AZKd0N0LcgnAlunATWxpXX5JPQVNP4GD4
VodAdCucKo0ckYCt7G6a48rsmc8dnZZz8LtbJqnk+vcrx25Y42Q1HdL3xj4D
.X5TB3CgRbOhhahCIyLcDGi92RHnOPajiU40sXxnqSJZjp+7Uu5Cvp0YU+iY
pNdea4PvygubWvQEdKoSPYGJc78Gp1pyXpoaa3xMmryXp7zApjJLaxjjFaN5
nqTr97CwoHcRH5O03IWXmJnUe7gaEzl5LZvmElik7Nn8ESWfbP4HAeCYUETu
JjQoWBypu4jx5Hyvv1u87HIyIPf5TvUWeqfN1WfFlj3.ywR9FzHeA5hTGTNR
vyPFME6YH7hP1D+MIU2j95qQV3q0KsvMBY0wv8DjAFC4B3akP4YNvNO61gct
ufcbJzAnik7OrQdC1llAXOR5Jv1rAIto4YRamcp0HVlzvSb8F6YK0hTF+397
gsjmoCiOV2CtUlDgfb3z.gujaNgXXMWlh.qmZOFjbl+8c+CfWnHZy
-----------end_max5_patcher-----------
`
