### ISSUE TITLE
Max 8 compatibility: live.dial, message, umenu, meter~ are not rendered

### ISSUE THREAD

**Issue by benbrackenc74** [Cycling74/miraweb#138] opened 2018-10-25 22:23 UTC
Going through the mira.frame help patcher, the following objects are no rendered in the browser:
- live.dial
- message
- umenu
- meter~

Haven't done any excavation, and there are not errors in the Max Console or browser console.

**Comment by benbrackenc74** [comment] 2018-10-26 18:45
It appears that in the case of message and umenu, it has something to do with their gradient usage. Touch any color attr and they will get rendered.

In the cases of live.dial and meter~, their constructors and paint methods are never hit. If you put a post at the top of live.dial, it will post, but it never reaches the class definitions, which makes me think there is something amiss deeper in the registration of EventEmitter or something.

**Comment by starakaj** [comment] 2018-11-02 20:00
Thanks for reporting this. Paint won't get called until all of the attributes are set, so I'm guessing something has changed such that Max 8 isn't sending all the attributes anymore.

**Comment by starakaj** [comment] 2018-11-02 20:28
Alright.... I'm having some trouble building miraweb.... but I'm looking into this

**Comment by starakaj** [comment] 2018-11-05 15:36
Okay, figured out the building issues. Not clear why they didn't come up before, florian thinks lerna might have changed somehow. Anyway, the issue is exactly what we thought: Max 8 no longer defines certain attributes. Making those attributes optional is an easy fix, working on that now.

**Comment by starakaj** [comment] 2018-11-05 15:54
Panel is actually a problem child as well—anything with a gradient is gonna be an issue.

**Comment by starakaj** [comment] 2018-11-05 16:15
Alright, I'm gonna close and make a new ticket for meter~. The issue here is much more complex than for the other objects, and is gonna require an update to the meter~ object itself in Max. Basically, the update to multichannel meter~ got rid of a pseudoparameter that would update whenever the object redrew its levels. So we at least need to update the object not to break old functionality, as a spotgap, and then we can think about maybe updating meter~ for multichannel, which I'm sure some people would be really happy about.

**Comment by fde31** [comment] 2018-11-07 09:52
Not sure why this was closed as this hasn't been merged fully yet. So yeah, reopening here. @starakaj I assume this is the work of PR #140

**Comment by fde31** [comment] 2018-11-07 10:06
merged in PR #140, which leaves us with meter~ from #141 . will close this ticket. @starakaj please consider working on dev for these kind of things or on a feature branch for proper PR's for the future. Thanks.

**Closed by fde31** 2018-11-07 10:06 UTC
Labels: Component: MiraWeb, Type: Bug
