### ISSUE TITLE
live.text as button not round in miraweb

### ISSUE THREAD

**Issue by 1offby** [Cycling74/miraweb#47] opened 2017-02-11 04:00 UTC
Max 7.3.2 beta 6bf7de6 x64  
Mira v 1.2.0  
Miraweb v 1.1.0  
mac OS 10.12.3  
iOS 10.2.1  

Live.text in button mode is displayed as rectangle in miraweb. Should be round. Mira app shows live.text as round in button mode.

<pre><code>
----------begin_max5_patcher----------
216.3ocWOErqBCBD7L7UP3bsg1mVMuekWLFJkWEsEZ1BllX7eW1s1KxgMYFl
Y2YdxYx1vhcVJ9U7mfwdxYLhBIXevL4ndwLnmIYxQGnK+GziVYw52tde.rlA
m4Npn5CsOM57C1HYSsosiVRn81t5M+sZy8dHj7ceYOjhe6eRGMWc99K4CFWi
c09RUgnRgy5CMkJ70jYNUWpDmQeu3bbHNm2hTOM8vBytfmZI1wbCuE.Ddrff
N+J7GBB1GtM80DiFxoHliPBrTgVZ1KWsF5rfO4npvwK+h+FJcVk4
-----------end_max5_patcher-----------
</code></pre>

**Comment by 1offby** [comment] 2017-02-11 07:13
...Possible that other features of live.text in button mode are not reflected in MiraWeb.
For example: live.text as button still appears to toggle in MiraWeb.

**Comment by starakaj** [comment] 2017-02-11 13:42
Can reproduce. Indeed, the Mode attribute seems basically ignored by live.text.

**Comment by fde31** [comment] 2017-02-18 14:37
that's a duplicate of #35 moving the comments there and closing out

**Closed by fde31** 2017-02-18 14:37 UTC
Labels: Status: Duplicate, Type: Enhancement
